apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-jonathan
  namespace: default
spec:
  parentRefs:
    - name: constellation-gateway
      sectionName: https-jonnowang
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: portfolio-jonathan
          port: 4321
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: portfolio-jonathan-http-redirect
  namespace: default
spec:
  parentRefs:
  - name: constellation-gateway
    sectionName: http
  hostnames:
  - jonno.wang
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
