apiVersion: apps/v1
kind: Deployment
metadata:
  name: vert
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vert
      version: v1
  template:
    metadata:
      labels:
        app: vert
        version: v1
    spec:
      containers:
        - image: lhr.ocir.io/lrwuubtwxjma/constellation-images/vert:1.0.0
          imagePullPolicy: Always
          name: vert
          resources:
            requests:
              memory: "1024Mi"
              cpu: 300m
            limits:
              memory: "1024Mi"
              cpu: 300m
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
        - name: ocirsecret
