apiVersion: v1
kind: Service
metadata:
  name: vert
  namespace: default
  labels:
    app: vert
    service: vert
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5173
      targetPort: 80
  selector:
    app: vert
