apiVersion: v1
kind: Service
metadata:
  name: raffle
  namespace: default
  labels:
    app: raffle
    service: raffle
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5173
      targetPort: 3000
  selector:
    app: raffle
