apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: constellation-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: constellation-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        container:
          image: docker.io/envoyproxy/envoy:distroless-v1.34-latest
      envoyService:
        annotations:
          # Force proxy deployment to use these settings for deployment
          oci.oraclecloud.com/load-balancer-type: "nlb"
          # service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
          # service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
          # service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
